"""
1. Write a Python program to demonstrate the creation of variables and different data types.

        the program to demonstrate use to indentation,creation,vairables and data type.
"""
"""cerat vairable
variabl is name which can store a value  
        we can use vairable any where in program
"""
 
name = "yuvraj"
age = 21

print(f"name= {name}")
print(f"age= {age}")

#data type 


